services:
  - type: web
    name: reasoning-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python "reasoning agent/app.py"
    pythonVersion: 3.11
    envVars:
      - key: NEO4J_URI
        value: neo4j+s://ab88412c.databases.neo4j.io
      - key: neo4j
        value: neo4j
      - key: neo4j_password
        value: fF38IYJ5t11rEUYHSVuzS8aiKojPcGWNQXw0SKW4SG8
      - key: CHROMA_HOST
        value: ${CHROMA_HOST}
      - key: CHROMA_PORT
        value: ${CHROMA_PORT}
